RehersalReservation/Controllers/RehersalController.cs
using RehersalReservation.Models;
using Entity;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net;

namespace RehersalReservation.Controllers
{
    public class RehersalController : Controller
    {
        private IRehersalService rehersalService;
        private IRoomService roomService;
        public RehersalController(IRehersalService rehersalService, IRoomService roomService)
        {
            this.rehersalService = rehersalService;
            this.roomService = roomService;
        }
        public async Task<ActionResult> Rehersals()
        {
            IEnumerable<Entity.RehersalSpase> data = await this.rehersalService.GetRehersals();
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
            }
            IEnumerable<RehersalSpace> rehersalSpaces = data.Select(o =>
            new RehersalSpace
            {
                Adress = o.Adress,
                CityID = o.CityID,
                RehersalSpaseID = o.RehersalSpaseID,
                RehersalSpaseName = o.RehersalSpaseName
            }).ToList();
            return View(rehersalSpaces);
        }
        public async Task<ActionResult> Delete(int id)
        {
            IEnumerable<Entity.Room> data = await this.roomService.GetRoomByRehersalID(id);
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
            }
            if (data.Count() == 0)
            {
                await rehersalService.DeleteRehersal(id);
            }
            else
            {
                return Content(@"Нельзя удалить связанный объект");
            }
            return RedirectToAction("Rehersals");
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RehersalSpace rehersalSpace)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Model is bad");
            }
            await rehersalService.UpdateRehersal(new RehersalSpase
            {
                Adress = rehersalSpace.Adress,
                CityID = rehersalSpace.CityID,
                RehersalSpaseID = rehersalSpace.RehersalSpaseID,
                RehersalSpaseName = rehersalSpace.RehersalSpaseName
            });
            return RedirectToAction("Rehersals");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            Entity.RehersalSpase data = await this.rehersalService.GetRehersalByID(id);
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
            }
            RehersalSpace rehersalSpace = new RehersalSpace
            {
                Adress = data.Adress,
                CityID = data.CityID,
                RehersalSpaseID = data.RehersalSpaseID,
                RehersalSpaseName = data.RehersalSpaseName
            };
            return View(rehersalSpace);
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(RehersalSpace rehersalSpace)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Model is bad");
            }
            await rehersalService.InsertRehersal(new RehersalSpase
            {
                Adress = rehersalSpace.Adress,
                CityID = rehersalSpace.CityID,
                RehersalSpaseID = rehersalSpace.RehersalSpaseID,
                RehersalSpaseName = rehersalSpace.RehersalSpaseName
            });
            return RedirectToAction("Rehersals");
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> GetRehersalByCityID(int cityID)
        {
            IEnumerable<Entity.RehersalSpase> data = await this.rehersalService.GetRehersalByCityID(cityID);
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
            }
            IEnumerable<RehersalSpace> rehersalSpaces = data.Select(o =>
            new RehersalSpace
            {
                Adress = o.Adress,
                CityID = o.CityID,
                RehersalSpaseID = o.RehersalSpaseID,
                RehersalSpaseName = o.RehersalSpaseName
            }).ToList();
            return View(rehersalSpaces);
        }
    }
}

RehersalReservation/Controllers/RoomController.cs
using RehersalReservation.Models;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RehersalReservation.Controllers
{
    //[Authorize(Roles = "admin")]
    public class RoomController : Controller
    {
        private IRoomService roomService;
        public RoomController(IRoomService roomService)
        {
            this.roomService = roomService;
        }
        // GET: Room
        public async Task<ActionResult> Rooms()
        {
            {
                IEnumerable<Entity.Room> data = await this.roomService.GetRooms();
                IEnumerable<Room> rooms = data.Select(o =>
                new Room
                {
                    RehersalRoomID = o.RehersalRoomID,
                    RehersalSpaseID = o.RehersalSpaseID,
                    RehersalRoomName = o.RehersalRoomName,
                    RehersalRoomSize = o.RehersalRoomSize
                }).ToList();
                return View(rooms);
            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Room room)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Model is bad");
            }
            await roomService.InsertRoom(new Entity.Room
            {
                RehersalSpaseID = room.RehersalSpaseID,
                RehersalRoomName = room.RehersalRoomName,
                RehersalRoomSize = room.RehersalRoomSize
            });
            return RedirectToAction("Rooms");
        }
        [HttpPost]
        public async Task<ActionResult> Edit(Room room)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Model is bad");
            }
            await roomService.UpdateRoom(new Entity.Room
            {
                RehersalRoomID = room.RehersalRoomID,
                RehersalSpaseID = room.RehersalSpaseID,
                RehersalRoomName = room.RehersalRoomName,
                RehersalRoomSize = room.RehersalRoomSize
            });
            return RedirectToAction("Rooms");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            Entity.Room data = await this.roomService.GetRoomByID(id);
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
            }
            Room room = new Room
            {
                RehersalRoomID = data.RehersalRoomID,
                RehersalSpaseID = data.RehersalSpaseID,
                RehersalRoomName = data.RehersalRoomName,
                RehersalRoomSize = data.RehersalRoomSize
            };
            return View(room);
        }
        public async Task<ActionResult> Delete(int id)
        {
            await roomService.DeleteRoom(id);
            return RedirectToAction("Rooms");
        }
        [HttpGet]
        public async Task<ActionResult> GetRoomByRehersalID(int rehersalSpaceID)
        {
            {
                IEnumerable<Entity.Room> data = await this.roomService.GetRoomByRehersalID(rehersalSpaceID);
                if (data == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Data not found");
                }
                IEnumerable<Room> rooms = data.Select(o =>
                new Room
                {
                    RehersalRoomID = o.RehersalRoomID,
                    RehersalSpaseID = o.RehersalSpaseID,
                    RehersalRoomName = o.RehersalRoomName,
                    RehersalRoomSize = o.RehersalRoomSize
                }).ToList();
                return View(rooms);
            }
        }
    }
}

RehersalReservation/Views/Rehersal/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RehersalReservation/Views/Rehersal/Add.cshtml
@model RehersalReservation.Models.RehersalSpace

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RehersalSpace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RehersalSpaseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RehersalSpaseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RehersalSpaseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RehersalSpaseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RehersalSpaseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RehersalSpaseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Rehersals")
</div>

RehersalReservation/Views/Rehersal/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RehersalReservation/Views/Rehersal/Edit.cshtml
@model RehersalReservation.Models.RehersalSpace

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RehersalSpace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RehersalSpaseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RehersalSpaseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RehersalSpaseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RehersalSpaseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RehersalSpaseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RehersalSpaseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Rehersals")
</div>

RehersalReservation/Views/Rehersal/GetRehersalByCityID.cshtml
@model IEnumerable<RehersalReservation.Models.RehersalSpace>

@{
    ViewBag.Title = "Репетиционные базы города";
}

<h2>Репетиционные базы города</h2>

<p>
    @Html.ActionLink("Create New", "Add")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RehersalSpaseID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RehersalSpaseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adress)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RehersalSpaseID)
            </td>
            <td>

                @Html.ActionLink(item.RehersalSpaseName, "GetRoomByRehersalID", "Room", new { rehersalSpaceID = item.RehersalSpaseID }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RehersalSpaseID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RehersalSpaseID })
            </td>
        </tr>
    }

</table>

RehersalReservation/Views/Rehersal/Index.cshtml
@model IEnumerable<RehersalReservation.Models.RehersalSpace>

@using GridMvc.Html
@{
    ViewBag.Title = "Home Page";
}
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<div class="code-cut">
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(c => c.RehersalSpaseID).Titled("RehersalSpase ID").Filterable(true);
    columns.Add(c => c.RehersalSpaseName).Titled("RehersalSpaseName").Filterable(true);
    columns.Add(c => c.Adress).Titled("Adress").Filterable(true);
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Delete", "Delete", new { id = o.RehersalSpaseID }, new { onclick = "return confirm('Вы действительно хотите удалить?');" }));
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Edit", "Edit", new { id = o.RehersalSpaseID }));

}).WithPaging(10).Sortable(true)
    @Html.ActionLink("Add Rehersal Space", "Add", "Rehersal")
</div>

RehersalReservation/Views/Rehersal/Rehersals.cshtml
@model IEnumerable<RehersalReservation.Models.RehersalSpace>

@using GridMvc.Html
@{
    ViewBag.Title = "Home Page";
}
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

<div class="code-cut">
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(c => c.RehersalSpaseID).Titled("RehersalSpase ID").Filterable(true);
    columns.Add(c => c.RehersalSpaseName).Titled("RehersalSpaseName").Filterable(true);
    columns.Add(c => c.Adress).Titled("Adress").Filterable(true);
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Delete", "Delete", new { id = o.RehersalSpaseID }, new { onclick = "return confirm('Вы действительно хотите удалить?');" }));
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Edit", "Edit", new { id = o.RehersalSpaseID }));

}).WithPaging(10).Sortable(true)
    @Html.ActionLink("Add Rehersal Space", "Add", "Rehersal")
</div>